name: Upload release build

on:
  release:
    types:
      - created

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
      - name: checkout master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-dev --no-interaction --no-progress

      - name: Download phar-composer-1.4.0
        run: |
          wget https://github.com/clue/phar-composer/releases/download/v1.4.0/phar-composer-1.4.0.phar
          mv phar-composer-1.4.0.phar phar-composer
          chmod +x phar-composer

      - name: Build phar
        run: ./phar-composer build .

      - name: Upload phar
        uses: jasonetco/upload-to-release@v0.1.1
        with:
          args: database-graphviz.phar application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
